language: python

python:
  - 3.6

# run on Travis container-based infrastructure
dist: xenial
sudo: false

git:
  depth: 99999  # needs all commits to fetch all tags, could not find better solution

addons:
  postgresql: "10"
  apt:
    packages:
    - postgresql-10-postgis-2.4

install:
  - pip install -r requirements.txt

before_script:
  - $TRAVIS_BUILD_DIR/.build/travis_before_script.sh

script:
  - $TRAVIS_BUILD_DIR/.build/travis_script.sh

env:
  global:
    - secure: FVQ8V8yMT4kdA4OqHJML1LVka+0jW8a12fb6AB98/e7QpuV8216BWU7Hps3aTo4uPH/sYzh2oP0sBedHk3imS3Ep4LJ4VugFGZufPsj2w4GqOR8xaUZjw3v0HeZVq6u1X2j9pYFSklNwHUMBd9TS93HhFkultM8N40I6UAgRtEmPKp35gnSSR/4OhRhBLvi+VMy3HWmBFzm9GAD0XtL8uvg9osA8tL7PWK4EmvR9AcoqgXo1MINXbYx2YHFBnG2j8w4CdRJA97aLeg0Lw2moMizQmhmU+w1FgmDU22A/HSAQZngKCW+/7LBTZ8d4lAoB6KXvNs2oeff27U64SRwUseiY6DQEE8lPVJWClQ5bnUWJlkQpBoNJy24ykFoBx2qBZ205CwjpnTVAPEiGN11Xsw4mFvfpjyslpmI2cCYuOWneqr7ZL7c/2Rrgx/HwuFDsi57Q6QAQFn3kmbSOuOSOIMwZ7f7uZ7eUbea2lGPmT+demegO+WgWuM4Q0HAblgjYmUIj0OMj+t+CbBiF3sUr+kuUgPIdTm3uaQGJhqSDcKIBimMlHIajAJ7dTz/2aia1gQy4zBbev7JpwbgMY/cVkZBSRnhYYXU5ZW9oWjG+x7Ft5UlQ0ORsfO5Pq4GCtTIUuqgD8lUZYlzYKshpWiAeVbHX5xCM6DtvNcdNpZuE9Wc=

before_deploy:
  - ./.deploy/create_release.py

deploy:
  provider: releases
  api_key: $GH_TOKEN
  file_glob: true
  file: /tmp/qwat-*
  skip_cleanup: true
  on:
    tags: true
